apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-matchmaker-service
spec:
  selector:
    app: matchmaker
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
      {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  type: {{ .Values.service.type }}
